config/routes.rb
Rails.application.routes.draw do
  resources :historics, only: %i[index]

  get "certificates/find", to: "certificates#find", as: :find_certificate
  delete 'historics/:id', to: "historics#destroy", as: :historic

  root to: 'certificates#index'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :historics, only: %i[index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate.rb
class Certificate < ApplicationRecord   
    validates :url, presence: true
    validates :status, presence: true
end

app/models/historic.rb
class Historic < ApplicationRecord
    belongs_to :certificate
end

app/controllers/api/v1/historics_controller.rb
module Api::V1
  class HistoricsController < ApplicationController
    def index
      @historics = Historic.order(created_at: :asc)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  def index
    @certificates = Certificate.order :url
  end

  def find
    @url = params[:url]
    @certificates = Certificate.where "url like ?", "%#{@url}%"
    
    certificate_ids = @certificates.ids if @certificates.present?
    
    certificate_ids.each do |id|
      Historic.create!(certificate_id: id)
    end
  end
end

app/controllers/historics_controller.rb
class HistoricsController < ApplicationController
  def index
    @historics = Historic.order(created_at: :asc)
  end

  def destroy
    id = params[:id]
    Historic.destroy id
    flash[:success] = t('.flash.success')
    redirect_to historics_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/views/certificates/_certificate.html.erb
<% @certificates.each do |certificate| %>
  <table class="table table-bordered table-hover">
    <head>
      <tr>
        <th><%= t('.url') %></th>
        <th><%= t('.status') %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= certificate.url %></td>
        <td><%= certificate.status %></td>
      </tr>
    </tbody>
<% end %>

app/views/certificates/find.html.erb
<h1>Certificados</h1>
<html>
  <body>
    <%= render 'certificate' %>
  </body>
</html>

app/views/historics/index.html.erb
<h1><%= t('.title') %></h1>
<html>
  <body>
    <% @historics.each do |historic| %>
      <table class="table table-bordered table-hover">
        <thead>
         <tr>
          <th><%= t('.created_at') %></th>
          <th><%= t('.url') %></th>
          <th><%= t('.status') %></th>
          <th><%= t('.action') %></th>
         </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= historic.created_at %></td>
            <td><%= historic.certificate.url %></td>
            <td><%= historic.certificate.status %></td>
            <td><%= link_to "Remover", historic, method: :delete, 
                    class: 'btn btn-danger',
                    data: {confirm: t('.info.message_confirmation')}
                 %>
              </td>
          </tr>
        </tbody>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestEsx</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= nav_bar brand: "Certificados SSL", brand_link: root_url do %>
    <%= menu_group do %>
    <%= menu_item "Histórico", historics_path %>
    <% end %>
    <%= form_tag find_certificate_path, method: :get, class:"navbar-form navbar-right" do %>
      <div class='form-group'>
      <%= text_field_tag :url, @url, placeholder: 'Inserir URL',class:'form-control' %>
      <%= button_to "Buscar", nil, class:"btn btn-default"%>
      </div>
    <% end %>
  <% end %>

  <body>
    <div class="container">
      <%= yield %>
    </div> 
  </body>
</html>